"""Tests for the upgraded HTML report generated by HTMLReportBuilder.

Asserts against the fixture session at probe_traces/55c2121bed564c03aea0f1c696c6d9a0/.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

# ── Paths ──────────────────────────────────────────────────────────────────────

FIXTURE_SESSION_ID = "55c2121bed564c03aea0f1c696c6d9a0"
FIXTURE_DIR = (
    Path(__file__).resolve().parent.parent.parent  # project root
    / "probe_traces"
    / FIXTURE_SESSION_ID
)
TRACE_JSONL = FIXTURE_DIR / "trace.jsonl"
REPORT_HTML = FIXTURE_DIR / "report.html"


# ── Helpers ────────────────────────────────────────────────────────────────────


def _build_report() -> str:
    """Regenerate the fixture report.html from trace.jsonl and return its contents."""
    import sys

    sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))
    from probe.tracer import HTMLReportBuilder, TraceEvent

    events_raw = TRACE_JSONL.read_text(encoding="utf-8").strip().splitlines()
    events = [
        TraceEvent(
            **{k: v for k, v in json.loads(line).items()
               if k in ("step_type", "data", "timestamp", "event_id", "session_id")}
        )
        for line in events_raw
    ]
    builder = HTMLReportBuilder(events, FIXTURE_SESSION_ID)
    html = builder.build()
    REPORT_HTML.write_text(html, encoding="utf-8")
    return html


# ── Fixtures ───────────────────────────────────────────────────────────────────


@pytest.fixture(scope="module")
def report_html() -> str:
    """Return the contents of the fixture report.html, (re-)generating if needed."""
    if not TRACE_JSONL.exists():
        pytest.skip(f"Fixture trace not found: {TRACE_JSONL}")
    return _build_report()


# ── Tests ──────────────────────────────────────────────────────────────────────


class TestReportFileExists:
    def test_report_file_created(self, report_html: str) -> None:
        """report.html must exist on disk."""
        assert REPORT_HTML.exists(), f"report.html not found at {REPORT_HTML}"

    def test_report_size_above_5kb(self, report_html: str) -> None:
        """report.html must be larger than 5 KB."""
        size = REPORT_HTML.stat().st_size
        assert size > 5 * 1024, f"report.html is only {size} bytes (expected > 5120)"


class TestDecisionTree:
    def test_tree_node_or_svg_present(self, report_html: str) -> None:
        """Decision tree must use <svg> elements or class='tree-node' divs."""
        has_svg = "<svg" in report_html
        has_tree_node = 'class="tree-node"' in report_html
        assert has_svg or has_tree_node, (
            "Expected <svg or class='tree-node' in report.html for decision tree"
        )

    def test_no_ul_li_in_report(self, report_html: str) -> None:
        """The HTML report must not use <ul>/<li> list markup."""
        assert "<ul>" not in report_html and "<li>" not in report_html, (
            "Found <ul> or <li> in report.html — decision tree must not use list markup"
        )


class TestSyntaxHighlighting:
    def test_highlight_css_classes_defined(self, report_html: str) -> None:
        """CSS definitions for all 5 syntax-highlight classes must exist in <style>."""
        style_block = re.search(r'<style\b.*?</style>', report_html, re.DOTALL)
        assert style_block, "No <style> block found"
        css = style_block.group()
        for cls in (".kw", ".str", ".cmt", ".num", ".op"):
            assert cls in css, f"Missing CSS definition for '{cls}' in <style>"

    def test_highlight_applied_to_python_code_when_present(self, report_html: str) -> None:
        """When Python code appears (diff lines, stack frames, expressions), it is highlighted.

        This session has no patch/fix and empty stack frames, so zero occurrences is
        acceptable. What must NOT happen is highlighting applied to plain English text
        (e.g., reasoning or hypothesis statements containing English words like 'in',
        'from', 'is' that also happen to be Python keywords).
        """
        found = set(re.findall(r'class="(kw|str|cmt|num|op)"', report_html))
        # Zero is fine for sessions without diffs/stack-frames. Non-zero must be ≤ sane bound.
        total = len(re.findall(r'class="(kw|str|cmt|num|op)"', report_html))
        assert total < 500, f"Suspiciously many highlight spans ({total}); likely applied to prose text"


class TestNoExternalResources:
    def test_no_http_urls(self, report_html: str) -> None:
        """report.html must not reference any http(s):// URLs."""
        # Allow URLs that are only inside <script> string literals (data only)
        # For a stricter check, scan outside script/style blocks
        # Simple check: look for http:// or https:// in attribute values / tag content
        # We check the whole file but exclude JS string contents inside <script> blocks
        outside_script = re.sub(r'<script\b.*?</script>', '', report_html, flags=re.DOTALL)
        outside_style = re.sub(r'<style\b.*?</style>', '', outside_script, flags=re.DOTALL)
        matches = re.findall(r'https?://', outside_style)
        assert not matches, (
            f"Found external URLs in HTML (outside script/style): {matches}"
        )

    def test_no_external_src_or_href(self, report_html: str) -> None:
        """No <link>, <script>, <img>, or <iframe> must reference an external URL."""
        external_refs = re.findall(
            r'<(?:link|script|img|iframe)[^>]+(?:src|href)\s*=\s*["\']?https?://',
            report_html,
            re.IGNORECASE,
        )
        assert not external_refs, (
            f"Found external src/href references: {external_refs}"
        )


class TestCoreSectionsPresent:
    @pytest.mark.parametrize("section", ["Hypotheses", "Evidence", "Patch", "Timeline"])
    def test_section_present(self, report_html: str, section: str) -> None:
        """Each of the four core section headings must appear in the report."""
        assert section in report_html, (
            f"Expected section '{section}' to be present in report.html"
        )
